SDSP/Models/RealTime_InTransit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SDSP.Models
{
    public class RealTime_InTransit
    {
        public long Id { get; set; }
        public string Hazmat { get; set; }
        public Nullable<System.DateTime> UnloadDate { get; set; }
        public string RouteRun { get; set; }
        public string Route { get; set; }
        public string Run { get; set; }
        public string PuRoute2 { get; set; }
        public string RouteType { get; set; }
        public string RouteMiles { get; set; }
        public string LegMiles { get; set; }
        public string Seq { get; set; }
        public string SName { get; set; }
        public string LDK { get; set; }
        public string LogisticsPointId { get; set; }
        public Nullable<System.DateTime> ArrvDate { get; set; }
        public Nullable<System.TimeSpan> ArrvTime { get; set; }
        public Nullable<System.DateTime> DepDate { get; set; }
        public Nullable<System.TimeSpan> DepTime { get; set; }
        public string Timezone { get; set; }
        public string RoutesMilestone { get; set; }
        public string Day { get; set; }
        public int PeriodId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string TrailerNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<int> DataSourceId { get; set; }
        public Nullable<int> ExpressPriority { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> PullAhead { get; set; }
        public Nullable<System.DateTime> ingateTime { get; set; }
        public Nullable<int> ingatespot { get; set; }
        public Nullable<long> ingatedriver { get; set; }
        public Nullable<System.DateTime> preTime { get; set; }
        public Nullable<long> predriver { get; set; }
        public Nullable<System.DateTime> outTime { get; set; }
        public Nullable<long> outDriver { get; set; }
        public Nullable<int> IdPreingateBC { get; set; }
        public Nullable<int> IdRouteMaster { get; set; }
        public Nullable<System.DateTime> PreIngateBCDate { get; set; }
        public string PreIngateBCSpot { get; set; }
        public Nullable<int> IngateBCId { get; set; }
        public Nullable<int> IngateBCRouteMasterId { get; set; }
        public Nullable<System.DateTime> IngateBcDateTime { get; set; }
        public string IngateBCSpot { get; set; }
        public string DriverName { get; set; }
        public Nullable<long> DriverIdCompany { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string DriverCode { get; set; }
    }
}

SDSP/Models/YardStatu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SDSP.Models
{
    public class YardStatu
    {
        public int Id { get; set; }
        public Nullable<int> SpotStatusId { get; set; }
        public string Hazmat { get; set; }
        public string Route { get; set; }
        public string Run { get; set; }
        public string TrailerNumber { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> IngateDateTime { get; set; }
        public Nullable<int> Bound { get; set; }
        public Nullable<long> IngateId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> YardSpotId { get; set; }
        public Nullable<long> RouteMasterId { get; set; }
        public string Status { get; set; }
    }
}

SDSP/Controllers/YardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SDSP.Models;
using SDSP.Class;
using SpreadsheetLight;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNet.Identity;

namespace SDSP.Controllers
{
    [Authorize]
    public class YardController : Controller
    {
        ServiceReference1.SDSPServiceClient wcf = new ServiceReference1.SDSPServiceClient();
        DataSourceHelper dsh = new DataSourceHelper();
        // GET: Yard
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Inventory()
        {
            return View();
        }

        public ActionResult SpotManager()
        {
            List<YardSpot> SpotsList = new List<YardSpot>();

            var spotlst = wcf.getYardSpots(0);

            foreach (var item in spotlst)
            {
                YardSpot lst = new YardSpot();
                lst.Id = item.Id;
                lst.SpotNumber = item.SpotNumber;
                lst.SpotStatusId = item.SpotStatusId;
                SpotsList.Add(lst);
            }

            return View(SpotsList);
        }

        public JsonResult blockspots(int spot, int status, string comment)
        {
            string user = User.Identity.GetUserId();

            bool result = wcf.blockspots(spot, status, comment, user);


            return Json(new { saved = result });
        }

        public JsonResult getReason(int spot)
        {

            string reason = wcf.getReason(spot);

            return Json(new { reason = reason });
        }

        public ActionResult YardStatus()
        {
            List<YardSpot> SpotsList = new List<YardSpot>();

            SpotsList = dsh.getAllSpots();

            List<PrintHookVM> lstContenedoresEnYarda = new List<PrintHookVM>();

            var activeIngates = wcf.getactiveIngates();

            foreach (var item in activeIngates)
            {
                PrintHookVM phObj = new PrintHookVM();

                phObj.Ingate = new Ingate
                {
                    YardSpotId = item.Ingate.YardSpotId,
                    RouteMasterId = item.Ingate.RouteMasterId,
                    DateTime = item.Ingate.DateTime,
                    TrailerStatusId = item.Ingate.TrailerStatusId,
                    Bound = item.Ingate.Bound
                };

                phObj.RouteMaster = new RouteMaster
                {
                    Id = item.RouteMaster.Id,
                    Route = item.RouteMaster.Route,
                    Run = item.RouteMaster.Run,
                    UnloadDate = item.RouteMaster.UnloadDate,
                    Hazmat = item.RouteMaster.Hazmat,
                    Invoice = item.RouteMaster.Invoice,
                    Priority = item.RouteMaster.Priority,
                    TrailerNumber = item.RouteMaster.TrailerNumber,
                    Comments = item.RouteMaster.Comments
                };

                if (item.PreOutgate != null)
                {
                    phObj.PreOutgate = new PreOutgate
                    {
                        RouteMasterId = item.PreOutgate.RouteMasterId,
                        Id = item.PreOutgate.Id
                    };

                    phObj.Driver = new Driver
                    {
                        Id = item.Driver.Id,
                        Name = item.Driver.Name
                    };
                    phObj.Company = new Company
                    {
                        Name = item.Company.Name
                    };
                }

                lstContenedoresEnYarda.Add(phObj);
            }

            ViewBag.DriverId = dsh.getDrivers();

            ViewBag.CompanyId = dsh.getCompanies();

            ViewBag.YardSpotId = dsh.getSpotstoChange();

            YardStatusVM viewObj = new YardStatusVM
            {
                listContenedoresenYarda = lstContenedoresEnYarda,
                listSpots = SpotsList
            };

            return View(viewObj);
        }

        public JsonResult saveYardComment(string comment, long routeMasterid)
        {

            string user = User.Identity.GetUserId();

            var result = wcf.saveYardComment(comment, routeMasterid, user);

            return Json(new { saved = result });
        }

        public JsonResult getYardComments(long routeMasterId)
        {
            List<YardComment> commentlist = new List<YardComment>();
            var results = wcf.getYardComments(routeMasterId);

            foreach (var item in results)
            {
                YardComment commentdata = new YardComment
                {
                    AspNetUsersId = item.AspNetUsersId,
                    Comment = item.Comment,
                    DateTime = item.DateTime
                };

                commentlist.Add(commentdata);
            }

            return Json(commentlist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult updateDriver(int preoutgateId, int newDriver)
        {
            string user = User.Identity.GetUserId();

            var updated = wcf.updateAssignedDriver(preoutgateId, newDriver, user);

            string driver = wcf.getDriverAssigned(updated);

            return Json(driver, JsonRequestBehavior.AllowGet);
        }

        public JsonResult assignDriver(long? routeMasterid, long? newDriver)
        {
            string AspNetUsersId = User.Identity.GetUserId();

            long? assigned = wcf.SavePreOutGate(routeMasterid, newDriver, AspNetUsersId);

            string driver = wcf.getDriverAssigned(assigned);

            return Json(driver, JsonRequestBehavior.AllowGet);
        }

        public ActionResult expectedArrivals()
        {
            var result = wcf.getExpected();
            List<RouteMaster> expected = new List<RouteMaster>();
            foreach (var item in result)
            {
                RouteMaster rmObj = new RouteMaster
                {
                    Id = item.Id,
                    UnloadDate = item.UnloadDate,
                    Priority = item.Priority,
                    Route = item.Route,
                    Run = item.Run,
                    Comments = item.Comments,
                    TrailerNumber = item.TrailerNumber,
                    Invoice = item.Invoice
                };

                expected.Add(rmObj);
            }

            return View(expected);
        }

        public ActionResult PlanAudit()
        {
            ViewBag.type = dsh.getMissingExceding();

            PlanAuditVM obj = new PlanAuditVM
            {
                ListRouteMaster = null
            };

            return View(obj);
        }

        [HttpPost]
        public ActionResult PlanAudit(PlanAuditVM planObj)
        {
            List<RouteMaster> lrmObj = new List<RouteMaster>();
            ViewBag.type = dsh.getMissingExceding();
            if (ModelState.IsValid)
            {
                var Trailers = wcf.AuditTrailers(planObj.startDate, planObj.endDate, planObj.type);

                List<RouteMaster> listRM = new List<RouteMaster>();
                foreach (var rm in Trailers)
                {
                    RouteMaster rmObj = new RouteMaster
                    {
                        Id = rm.Id,
                        Route = rm.Route,
                        Run = rm.Run,
                        UnloadDate = rm.UnloadDate,
                        Hazmat = rm.Hazmat,
                        Priority = rm.Priority,
                        TrailerNumber = rm.TrailerNumber,
                    };
                    listRM.Add(rmObj);
                }
                PlanAuditVM paObj = new PlanAuditVM
                {
                    ListRouteMaster = listRM,
                    startDate = planObj.startDate,
                    endDate = planObj.endDate,
                    type = planObj.type
                };
                return View(paObj);
            }

            PlanAuditVM obj = new PlanAuditVM
            {
                ListRouteMaster = null
            };

            return View(obj);
        }

        public ActionResult realtimeInTransit()
        {
            var getRealTime = wcf.getinTransitStatus();

            List<RealTime_InTransit> inTransitList = new List<RealTime_InTransit>();
            foreach (var item in getRealTime)
            {
                RealTime_InTransit rmObj = new RealTime_InTransit
                {
                    Id = item.Id,
                    TrailerNumber = item.TrailerNumber,
                    UnloadDate = item.UnloadDate,
                    Route = item.Route,
                    Run = item.Run,
                    Hazmat = item.Hazmat,
                    Comments = item.Comments,
                    Priority = item.Priority,
                    Invoice = item.Invoice,
                    ExpressPriority = item.ExpressPriority,
                    ingatedriver = item.ingatedriver,
                    ingateTime = item.ingateTime,
                    ingatespot = item.ingatespot,
                    predriver = item.predriver,
                    preTime = item.preTime,
                    outDriver = item.outDriver,
                    outTime = item.outTime,
                    PreIngateBCDate = item.PreIngateBCDate,
                    PreIngateBCSpot = item.PreIngateBCSpot,
                    IngateBcDateTime = item.IngateBcDateTime,
                    IngateBCSpot = item.IngateBCSpot,
                    DriverCode = item.DriverCode,
                    DriverName = item.DriverName,
                    ArrvTime = item.ArrvTime
                };

                inTransitList.Add(rmObj);
            }

            return View(inTransitList);
        }

        [AllowAnonymous]
        public ActionResult realtimeInTransitPublic()
        {
            var getRealTime = wcf.getinTransitStatus();

SDSP/Views/Yard/PlanAudit.cshtml
@model SDSP.Models.PlanAuditVM
@{
    ViewBag.Title = "Yard Audit";
}
@Styles.Render("~/Content/jqueryui")
<style>
    .blocked {
        color: white;
        background-color: #c3000d;
        height: 10px;
    }

    .inUse {
        color: white;
        background-color: #73ba37;
    }

    .available {
        height: 10px;
    }

    #blocked-square {
        color: #c3000d;
        font-size: 20px;
    }

    #inuse-square {
        color: #73ba37;
        font-size: 20px;
    }

    #available-square {
        /*color: white;*/
        font-size: 20px;
    }

    #tabs-1 {
        max-height: 230px;
        overflow-y: auto;
    }

    #Comment {
        height: 120px;
    }

    .ui-autocomplete.ui-menu {
        z-index: 3001;
    }

    .custom-combobox-input {
        width: 260px;
        height: 30px;
        background: white;
        border-radius: 3px;
        padding: 10px;
    }
    .no-display {
        display: none;
    }
</style>
    <div id="searchTerms" >
        <h2>Yard Audit Trailers</h2>
        @*<span id="blocked-square">&#9724;</span> Blocked
            <span id="inuse-square">&#9724;</span> In Use
            <span id="available-square">&#9723;</span> Available*@
        @using (Html.BeginForm("PlanAudit", "Yard", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        <div class="form-group">
            <label class="control-label col-md-2" for="startDate">Start Date</label>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.startDate, new { @class = "form-control datepicker", @type = "date" })
            </div>
            <div class="col-md-10 col-lg-offset-2">
                <span id="start-date-error" class="field-validation-valid text-danger" data-valmsg-for="startDate" data-valmsg-replace="true"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="endDate">End Date</label>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.endDate, new { @class = "form-control datepicker", @type = "date" })
            </div>
            <div class="col-md-10 col-lg-offset-2">
                <span id="end=date-error" class="field-validation-valid text-danger" data-valmsg-for="endDate" data-valmsg-replace="true"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="type">Report type</label>
            <div class="col-md-10">
                @Html.DropDownList("type", null, "Select", htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="col-md-10 col-lg-offset-2">
                <span id="type-error" class="field-validation-valid text-danger" data-valmsg-for="tyoe" data-valmsg-replace="true"></span>
            </div>
        </div>
        <button id="submitButton" type="submit">Get Report</button>
        }
    </div>
@if (Model.ListRouteMaster != null)
{
    if (Model.type == 1)
    {
        <h2>Missing Trailers for</h2>
    }
    else
    {
        <h2>Extra Trailers for</h2>
    }
    <div id="datatables">
        @for (DateTime date = Model.startDate; date <= Model.endDate; date = date.AddDays(1))
        {
        <h3>@date.ToShortDateString()</h3>
        <table id="Trailers" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Trailer</th>
                    <th>Route</th>
                    <th>Sequence</th>
                    <th>Unload Date</th>
                    <th>Priority</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var rm in Model.ListRouteMaster)
                {
                    if (rm.UnloadDate == date)
                    {
                        <tr>
                            <td>@rm.TrailerNumber</td>
                            <td>@rm.Route</td>
                            <td>@rm.Run</td>
                            <td>@rm.UnloadDate</td>
                            <td>@rm.Priority</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        }
    </div>

    <input type="submit" id="btnSubmit" value="Export to Excel" />
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customplanaudit")
}

SDSP/Views/Yard/SpotManager.cshtml
@model IEnumerable<SDSP.Models.YardSpot>
@{
    ViewBag.Title = "SpotManager";
}
@Styles.Render("~/Content/jqueryui")
<style>
     li {
        -webkit-touch-callout: none; /* iOS Safari */
        -webkit-user-select: none; /* Safari */
        -khtml-user-select: none; /* Konqueror HTML */
        -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
        user-select: none; /* Non-prefixed version, currently
                            supported by Chrome and Opera */
    }
    #feedback {
        font-size: 15px;
        font-weight: bolder;
    }

    #selectable .ui-selecting {
        background: red;
    }

    #selectable .selected {
        /*background: #F39814;*/
        background: red;
        color: white;
    }
    .inuse {
        background:#73ba37;
        color: white;
    }
    #selectable {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    #selectable li {
        margin: 1px;
        padding: 1px;
        float: left;
        width: 40px;
        height: 30px;
        font-size: 1.2em;
        text-align: center;
    }

    /*#select-container {
        width: 53%;
        overflow: auto;
        max-height: 190px;
        margin-bottom: 10px;
    }*/

    .custom-combobox-input {
        width: 280px;
        height: 30px;
        background: white;
        border-radius: 3px;
        padding: 10px;
    }

    #occurrences > tbody > tr:hover {
        background-color: #F39814;
        color: white;
    }
    #Comment {
        height:100px;
    }
    #blocked-square {
        color: #c3000d;
        font-size:20px;
    }
    #inuse-square{
        color: #73ba37;
        font-size:20px;
    }
    #available-square {
        /*color: white;*/
        font-size:20px;
    }
</style>

<h2>Block/Unblock spots</h2>
<p id="feedback">
    Click on a spot to block/unblock it, right click on blocked spots to see why its blocked.
</p>
<div id="divMessage" class="alert alert-success collapse">
    <a id="closeMessage" class="close" href="#">&times;</a>
    <h4 id="success-message" class="alert-heading">Saved successfully!</h4>
</div>
<div id="divError" class="alert alert-danger collapse">
    <a id="closeErrorMessage" class="close" href="#">&times;</a>
    <h4 id="errorText" class="alert-heading">No rows were selected</h4>
</div>
@Html.Hidden("YardSpotId")
@Html.Hidden("RouteMasterId", 0)
<span id="blocked-square">&#9724;</span> Blocked
<span id="inuse-square">&#9724;</span> In Use
<span id="available-square">&#9723;</span> Available

<div id="select-container">
    <ol id="selectable">
        @foreach (var item in Model)
        {
            switch (item.SpotStatusId)
            {
                case 1:
                    <li class="ui-widget-content selected" id="spot-@(item.SpotNumber)">@Html.Raw(item.SpotNumber)</li>
                    break;
                case 2:
                    <li class="ui-widget-content" id="spot-@(item.SpotNumber)">@Html.Raw(item.SpotNumber)</li>
                    break;
                case 3:
                    <li class="ui-widget-content inuse" id="inuse-@(item.SpotNumber)">@Html.Raw(item.SpotNumber)</li>
                    break;
            }

        }
    </ol>
</div>

<!-- Modal Comentarios -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close cerrar" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title" id="comment-title">Reasons</h2>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    @Html.Label("Please add a reason for the change", htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        @Html.TextArea("Comment", null, new { @class = "form-control" })
                    </div>
                </div> 
            </div>
            <div class="modal-footer">
                <button id="saveChange" type="button" class="btn btn-primary">Change status</button>
                <button type="button" class="btn btn-secondary cerrar" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
@*Modal Razones*@
<div class="modal fade" id="reasonModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title" id="occurences-title">Reasons</h2>
            </div>
            <div class="modal-body" id="reasonText">
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@*Modal confirmar*@
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title" id="delete-title">Confirm Unblock</h2>
            </div>
            <div class="modal-body">
                Are you sure you want to unblock the selected spot?
            </div>
            <div class="modal-footer">
                <button type="button" id="yes" class="btn btn-primary" data-dismiss="modal">Yes</button>
                <button type="button" id="no" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customspotmanager")
}

SDSP/Views/Yard/TrailerHistory.cshtml
@model SDSP.Models.TrailerMovements
@{
    ViewBag.Title = "Trailer History";
}
<style>
    #report-data {
        font-weight: bold;
        font-size: 15px;
    }

    #submitButton {
        margin-bottom: 20px;
    }
</style>
<h2>Trailer History</h2>

<div id="searchTerms">
    @using (Html.BeginForm("TrailerHistory", "Yard", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            <label class="control-label col-md-2" for="start">Start Date</label>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.start, new { @class = "form-control datepicker", @type = "date" })
            </div>
            <div class="col-md-10 col-lg-offset-2">
                <span id="start-date-error" class="field-validation-valid text-danger" data-valmsg-for="start" data-valmsg-replace="true"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="end">End Date</label>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.end, new { @class = "form-control datepicker", @type = "date" })
            </div>
            <div class="col-md-10 col-lg-offset-2">
                <span id="end=date-error" class="field-validation-valid text-danger" data-valmsg-for="end" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="TrailerNumber">Trailer number</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="false" data-val-number="" id="TrailerNumber" name="TrailerNumber" type="text" value="@Model.TrailerNumber" />
            </div>
            <div class="col-md-10 col-lg-offset-2">
                @Html.ValidationMessageFor(model => model.TrailerNumber, "", new { @class = "text-danger", @id = "trailer-error" })
            </div>
        </div>

        <button id="submitButton" type="submit">Get Report</button>
    }
</div>

@*<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title" id="delete-title">Confirm Delete</h2>
            </div>
            <div class="modal-body">
                Are you sure you want to delete the selected record?
            </div>
            <div class="modal-footer">
                <button type="button" id="yes" class="btn btn-primary" data-dismiss="modal">Yes</button>
                <button type="button" id="no" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>*@

@if (Model.THistory != null && Model.THistory.Count > 0)
{
    <span id="report-data">From @Model.start.ToShortDateString() to @Model.end.ToShortDateString()</span>
        <table id="Trailers" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Trailer</th>
                    <th>Route</th>
                    <th>Hazmat</th>
                    <th>Bound</th>
                    <th>Trailer Status</th>
                    <th>Type</th>
                    <th>Date & Time</th>
                    <th>Driver</th>                    
                </tr>
            </thead>
            <tbody>
                @foreach (var rm in Model.THistory)
                {
                    string bound = "";
                    if (rm.Bound == 1) { bound = "Southbound"; }
                    else if (rm.Bound == 2) { bound = "Northbound"; }
                    string type = "";
                    if (rm.Type == 1) { type = "Ingate"; }
                    else if (rm.Type == 2) { type = "Hook"; }
                    else if (rm.Type == 3) { type = "Outgate"; }
                    <tr id="@rm.RouteMasterId">
                        <td>@Model.TrailerNumber.ToUpper()</td>
                        <td>@rm.Route</td>
                        <td>@rm.Hazmat</td>
                        <td>@bound</td>
                        <td>@rm.TrailerStatus</td>
                        <td>@type</td>
                        <td>@rm.DateTime</td>
                        <td>@rm.Driver</td>                        
                    </tr>
                }
            </tbody>
        </table>

        <input type="submit" id="btnSubmit" value="Download as Excel" />
}
else
{
    <h2>No history found for the specified search terms.</h2>
}
<!-- Modal para Edicion/comentarios -->
<div class="modal fade" id="commentsModal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="comment-title">Comments</h2>
            </div>
            <div class="modal-body">                
                <table id="table-comments" class="table">
                    <thead>
                        <tr>
                            <th>Comment</th>
                            <th>Made by</th>
                            <th>Date & Time</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button id="close-comment" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/history")
}

SDSP/Views/Yard/forecastDplus3.cshtml
@{
    Layout = null;
}
@model IEnumerable<SDSP.Models.RealTime_InTransit>
<table>
    <thead>
        <tr>
            <th>Trailer </th>
            <th>Route-Sequence</th>
            <th>Unload Date</th>
            <th>Hazmat</th>
            <th>SDSP Spot</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>@item.TrailerNumber</td>
                <td>@item.RouteRun</td>
                <td>@item.UnloadDate.Value.ToString("MM/dd/yyyy")</td>
                <td>@item.Hazmat</td>
                <td>@item.ingatespot</td>
            </tr>
        }
    </tbody>
</table>