SDSP/Models/Ingate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SDSP.Models
{
    public class Ingate
    {
        public long Id { get; set; }
        public Nullable<long> RouteMasterId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }

        [Range(1, 295, ErrorMessage = "Please select a spot")]
        public Nullable<int> YardSpotId { get; set; }

        [Required(ErrorMessage = "Please select a driver from the list")]
        public Nullable<long> DriverId { get; set; }

        [Required(ErrorMessage = "Please select bound")]
        public Nullable<int> Bound { get; set; }
        public string AspNetUsersId { get; set; }

        [Required(ErrorMessage = "Please select a trailer status")]
        public Nullable<int> TrailerStatusId { get; set; }

        [Required(ErrorMessage = "Please enter a trailer number")]
        public string TrailerNumber { get; set; }

        public string Hazmat { get; set; }
    }

    public class PrintDropVM
    {
        public Driver Driver { get; set; }
        public Company Company { get; set; }
        public Ingate Ingate { get; set; }
        public RouteMaster RouteMaster { get; set; }
    }

    public class IngateTrailersVM
    {
        public Ingate Ingate { get; set; }
        public RouteMaster RouteMaster { get; set; }
        public Comment Comment { get; set; }
    }

}

SDSP/Models/IngatesReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SDSP.Models
{
    public class IngatesReport
    {
        public long Id { get; set; }
        public Nullable<long> IngateRouteMasterId { get; set; }
        public Nullable<System.DateTime> IngateDateTime { get; set; }
        public string AspNetUsersId { get; set; }
        public Nullable<int> YardSpotId { get; set; }
        public Nullable<long> IngateDriverId { get; set; }
        public Nullable<int> Bound { get; set; }
        public long idDriver { get; set; }
        public Nullable<long> IdCamex { get; set; }
        public string DriverName { get; set; }
        public Nullable<long> IdCompany { get; set; }
        public string DriverUserId { get; set; }
        public long CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyUserId { get; set; }
        public long IdRouteMaster { get; set; }
        public string Hazmat { get; set; }
        public Nullable<System.DateTime> UnloadDate { get; set; }
        public string RouteRun { get; set; }
        public string Route { get; set; }
        public string Run { get; set; }
        public string PuRoute2 { get; set; }
        public string RouteType { get; set; }
        public string RouteMiles { get; set; }
        public string LegMiles { get; set; }
        public string Seq { get; set; }
        public string SName { get; set; }
        public string LDK { get; set; }
        public string LogisticsPointId { get; set; }
        public Nullable<System.DateTime> ArrvDate { get; set; }
        public Nullable<System.TimeSpan> ArrvTime { get; set; }
        public Nullable<System.DateTime> DepDate { get; set; }
        public Nullable<System.TimeSpan> DepTime { get; set; }
        public string Timezone { get; set; }
        public string RoutesMilestone { get; set; }
        public string Day { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string TrailerNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<int> DataSourceId { get; set; }
        public Nullable<int> ExpressPriority { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> PullAhead { get; set; }
        public Nullable<int> TrailerStatusId { get; set; }
        public string TrailerStatusName { get; set; }
    }

    public class IngatesReportVM
    {
        public DateTime startDate { get; set; }
        public DateTime endDate { get; set; }
        public List<IngatesReport> ingatesReport { get; set; }
    }
}

SDSP/Controllers/IngatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SDSP.Models;
using System.Diagnostics;
using Newtonsoft.Json.Linq;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System.Text.RegularExpressions;
using SDSP.Class;
using System.Text;
using SpreadsheetLight;

namespace SDSP.Controllers
{
    [Authorize]
    public class IngatesController : Controller
    {
        ServiceReference1.SDSPServiceClient wcf = new ServiceReference1.SDSPServiceClient();
        //private SDSPEntities db = new SDSPEntities();
        DataSourceHelper dsh = new DataSourceHelper();

        // GET: Ingates
        public ActionResult Index()
        {
            return View();
        }

        // GET: Ingates/Details/5
        public ActionResult Details(long? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            Ingate ingate = new Ingate();
            //if (ingate == null)
            //{
            //    return HttpNotFound();
            //}
            return View(ingate);
        }       

        // GET: Ingates/Create
        public ActionResult Create(int? error)
        {
            ViewBag.YardSpotId = dsh.getSpots();

            ViewBag.DriverId = dsh.getDrivers();

            ViewBag.CompanyId = dsh.getCompanies();

            ViewBag.Bound = dsh.getBound();

            ViewBag.TrailerStatusId = dsh.getTrailerStatus();

            ViewBag.Hazmat = dsh.getHazmat();

            if (error == null)
            {
                ViewBag.Error = -1;
            }
            else
            {
                ViewBag.Error = (error > 0) ? error : 0;
            }

            return View();
        }

        // POST: Ingates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ingate ingate)
        {
            ingate.AspNetUsersId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                long? driverId = ingate.DriverId;
                long? ingateId = 0;

                ingateId = (ingate.RouteMasterId > 0) ? wcf.SaveIngate(ingate.RouteMasterId, ingate.AspNetUsersId, ingate.YardSpotId, ingate.DriverId, ingate.Bound, ingate.TrailerStatusId) : wcf.saveManualIngate(ingate.AspNetUsersId, ingate.YardSpotId, ingate.Hazmat, ingate.DriverId, Request["TrailerNumber"], Request["Route"], Request["Sequence"],"0", "", ingate.Bound, ingate.TrailerStatusId);
                if (ingateId > -1)
                {
                    if (wcf.SaveIngateComment(Request["Comments"], ingateId, ingate.AspNetUsersId))
                    {                                                
                        bool hook = (Request["Hook"] != "false");
                        bool print = (Request["Print"] != "false");

                        if (!hook)
                        {
                            return (!print) ? RedirectToAction("Create", new { error = 0 }) : RedirectToAction("PrintHook", "PreOutgates", new { id = 0, ingateid = ingateId });
                        }
                        else
                        {
                            return RedirectToAction("create", "PreOutgates", new { ingateid = ingateId, driverid = driverId, print = print });
                        }
                    }
                }
                else
                {
                    if (ingateId == -2)
                    {
                        //Spot repetido
                        ViewBag.Error = 2;
                    }
                    else if (ingateId == -1)
                    {
                        //Caja repetida
                        ViewBag.Error = 1;
                    }
                }
            }
            else {
                //Missing info
                ViewBag.Error = 3;
            }

            ViewBag.YardSpotId = dsh.getSpots();

            ViewBag.DriverId = dsh.getDrivers();

            ViewBag.CompanyId = dsh.getCompanies();

            ViewBag.Bound = dsh.getBound();

            ViewBag.TrailerStatusId = dsh.getTrailerStatus();

            ViewBag.Hazmat = dsh.getHazmat();

            return View(ingate);
        }

        // GET: Ingates/Edit/5
        public ActionResult Edit(long? id)
        {

            IngateTrailersVM itObj = new IngateTrailersVM();

            ViewBag.YardSpotId = dsh.getEditingateSpots(id);

            ViewBag.DriverId = dsh.getDrivers();

            ViewBag.CompanyId = dsh.getCompanies();

            ViewBag.Bound = dsh.getBound();

            ViewBag.TrailerStatusId = dsh.getTrailerStatus();

            var itResult = wcf.getIngatebyId(id);

            itObj.Ingate = new Ingate {
                Id = itResult.Ingate.Id,
                DateTime = itResult.Ingate.DateTime,
                DriverId = itResult.Ingate.DriverId,
                Bound = itResult.Ingate.Bound,
                TrailerStatusId = itResult.Ingate.TrailerStatusId
            };
            itObj.RouteMaster = new RouteMaster {
                Id = itResult.RouteMaster.Id,
                TrailerNumber = itResult.RouteMaster.TrailerNumber,
                Hazmat = itResult.RouteMaster.Hazmat,
                Route = itResult.RouteMaster.Route,
                Run = itResult.RouteMaster.Run,
                Priority = itResult.RouteMaster.Priority,
                Invoice = itResult.RouteMaster.Invoice
            };

            //ViewBag.Hazmat = dsh.getHazmat();

            return View(itObj);
        }

        // POST: Ingates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RouteMasterId,DateTime,UserId,YardSpotId")] Ingate ingate)
        {
            //if (ModelState.IsValid)
            //{
            //    db.Entry(ingate).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //ViewBag.YardSpotId = new SelectList(db.YardSpots, "Id", "TrailerNumber", ingate.YardSpotId);
            return View(ingate);
        }

        // GET: Ingates/Delete/5
        public JsonResult Delete(long? id)
        {
            string user = User.Identity.GetUserId();
            int ingate = wcf.deleteIngate(id, user);

            return Json(new { deleted = ingate });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult FindDrivers(string term) {
            //var resultado = db.Drivers.Where(x => x.Name.Contains(term)).Select(x => x.Name).Take(5).ToList();
            return Json("kk", JsonRequestBehavior.AllowGet);
        }

        public JsonResult getRouteMasterData(string trailer) {
            List<NorthTrailer> lstNorthTrailer = new List<NorthTrailer>();
            string trailerWithSpaces = Regex.Replace(trailer, @"(\p{L})(\d)", "$1 $2");

            var wcfResult = wcf.getRouteMasterDatabyTrailerNumber(trailerWithSpaces);

            if (wcfResult.Count() == 0)
            {
                wcfResult = wcf.getRouteMasterDatabyTrailerNumber(trailer);
            }

            foreach (var item in wcfResult)
            {
                RouteMaster RouteMaster = new RouteMaster {
                    Id = item.Id,
                    TrailerNumber = item.TrailerNumber,
                    Run = item.Run,
                    Route = item.Route,
                    Priority = item.Priority,
                    UnloadDate = item.UnloadDate,
                    Hazmat = item.Hazmat,
                    Invoice = item.Invoice,
                    DataSourceId = item.DataSourceId,
                };

                Northbound north = new Northbound { };
                if (RouteMaster.DataSourceId == 9)
                {
                    //Viene de LLP
                    var n = wcf.getNorthInfo(RouteMaster.Id);
                    north = new Northbound
                    {
                        RouteMasterId = n.RouteMasterId,
                        TrailerStatusId = n.TrailerStatusId,
                        DriverId = n.DriverId
                    };

                }
                else
                {
                    north = null;
                }

                NorthTrailer nTrailer = new NorthTrailer {
                    RouteMaster = RouteMaster,
                    Northbound = north
                };
                
               
                lstNorthTrailer.Add(nTrailer);
            }
            return Json(lstNorthTrailer, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getSingleRouteMasterData(long routeMasterId)
        {
            var wcfResult = wcf.getSingleRouteMasterData(routeMasterId);
            RouteMaster rM = new RouteMaster {
                Id = wcfResult.Id,
                TrailerNumber = wcfResult.TrailerNumber,
                Run = wcfResult.Run,
                Route = wcfResult.Route,
                Priority = wcfResult.Priority,
                UnloadDate = wcfResult.UnloadDate,
                Hazmat = wcfResult.Hazmat,
                Invoice = wcfResult.Invoice,
                DataSourceId = wcfResult.DataSourceId,
            };

            Northbound north = new Northbound { };
            if (rM.DataSourceId == 9)
            {

SDSP/Views/Ingates/Delete.cshtml
@model SDSP.Models.Ingate

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ingate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlanId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlanId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YardSpot.TrailerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YardSpot.TrailerNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SDSP/Views/Ingates/Details.cshtml
@model SDSP.Models.Ingate

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ingate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlanId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlanId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YardSpot.TrailerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YardSpot.TrailerNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SDSP/Views/Ingates/Index.cshtml
@model IEnumerable<SDSP.Models.Ingate>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUsersId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DriverId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YardSpotId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUsersId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DriverId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YardSpotId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

SDSP/Views/Ingates/checkSpot.cshtml
@{
    ViewBag.Title = "checkSpot";
}

<h2>checkSpot</h2>

@ViewBag.resultado

SDSP/Views/Ingates/ingatesReport.cshtml
@model SDSP.Models.IngatesReportVM
@{
    ViewBag.Title = "ingatesReport";
}
<style>
    #report-data {
        font-weight: bold;
        font-size: 15px;
    }

    #submitButton {
    margin-bottom:20px;
    }

</style>
<h2>Ingates Report</h2>

    <div id="searchTerms">        
        @using (Html.BeginForm("ingatesReport", "Ingates", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                <label class="control-label col-md-2" for="startDate">Start Date</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.startDate, new { @class = "form-control datepicker", @type = "date" })
                </div>
                <div class="col-md-10 col-lg-offset-2">
                    <span id="start-date-error" class="field-validation-valid text-danger" data-valmsg-for="startDate" data-valmsg-replace="true"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="endDate">End Date</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.endDate, new { @class = "form-control datepicker", @type = "date" })
                </div>
                <div class="col-md-10 col-lg-offset-2">
                    <span id="end=date-error" class="field-validation-valid text-danger" data-valmsg-for="endDate" data-valmsg-replace="true"></span>
                </div>
            </div>
            <button id="submitButton" type="submit">Get Report</button>
        }
    </div>

    <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h2 class="modal-title" id="delete-title">Confirm Delete</h2>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete the selected record?
                </div>
                <div class="modal-footer">
                    <button type="button" id="yes" class="btn btn-primary" data-dismiss="modal">Yes</button>
                    <button type="button" id="no" class="btn btn-secondary" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>

    @if (Model.ingatesReport.Count > 0)
    {
        <span id="report-data">From @Model.startDate.ToShortDateString() to @Model.endDate.ToShortDateString()</span>
        <div id="divMessage" class="alert alert-success collapse">
            <a id="closeMessage" class="close" href="#">&times;</a>
            <h4 class="alert-heading">Deleted successfully!</h4>
        </div>
        <label style="margin-left: 15px;">Search</label><input id="search" type="text" placeholder="Trailer #" />
        <table id="Trailers" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Trailer</th>
                    <th>Route</th>
                    <th>Sequence</th>
                    <th>Unload Date</th>
                    <th>Ingate Date & Time</th>
                    <th>Driver</th>
                    <th>Bound</th>
                    <th>Trailer Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>                
                @foreach (var rm in Model.ingatesReport)
                {
                    string bound = (rm.Bound == 1) ? "Southbound" : "Northbound";
                    <tr>
                        <td>@rm.TrailerNumber</td>
                        <td>@rm.Route</td>
                        <td>@rm.Run</td>
                        <td>@rm.UnloadDate</td>
                        <td>@rm.IngateDateTime</td>
                        <td>@rm.DriverName</td>
                        <td>@bound</td>
                        <td>@rm.TrailerStatusName</td>
                        <td>
                            @*@Html.ActionLink("Edit", "Edit", new { id = rm.Id }) |*@                            
                            <a id="Delete-@rm.Id" href="#">Delete</a>
                            @*@Html.ActionLink("Delete", "Delete", new { id = rm.Id })*@
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <input type="submit" id="btnSubmit" value="Export to Excel" />

        @*Modal error*@
        <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h2 class="modal-title" id="tituloModal">Error!</h2>
                    </div>
                    <div class="modal-body">
                        <div id="errorText" class="alert alert-danger" role="alert">
                            You cannot delete an ingate for a trailer that has been dispatched.
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <h2>No in gate data found for the specified dates.</h2>
    }


@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ingatesReport")
}