SDSP/Controllers/SourcesController.cs
using Microsoft.AspNet.Identity;
using SDSP.Class;
using SDSP.Models;
using SpreadsheetLight;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Script.Serialization;

namespace SDSP.Controllers
{
    [Authorize]
    public class SourcesController : Controller
    {
        ServiceReference1.SDSPServiceClient wcf = new ServiceReference1.SDSPServiceClient();
        DataSourceHelper dsh = new DataSourceHelper();
        public ActionResult UploadInTransit()
        {
            return View();
        }

        public DataTable ConvertToDatatable<T>(IList<T> data)
        {
            var props = TypeDescriptor.GetProperties(typeof(T));
            DataTable table = new DataTable { TableName = "TempTable" };
            foreach (PropertyDescriptor prop in props)
                table.Columns.Add(prop.Name, Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType);
            foreach (T item in data)
            {
                DataRow row = table.NewRow();
                foreach (PropertyDescriptor prop in props)
                    row[prop.Name] = prop.GetValue(item) ?? DBNull.Value;
                table.Rows.Add(row);
            }
            return table;
        }

        public ActionResult UploadRouteMaster()
        {
            ViewBag.Error = 0;
            return View();
        }

        [HttpPost]
        public ActionResult UploadRouteMaster(RouteMasterExcel importExcel) {
            if (ModelState.IsValid)
            {
                int periodId = wcf.savePeriod(importExcel.period, importExcel.StartDate);

                if (periodId > 0)
                {
                    string dateStamp = DateTime.Now.ToString("yyyyMMddHHmmss");
                    string path = Server.MapPath("~/Content/Uploads/" + dateStamp + "-" + importExcel.file.FileName);
                    importExcel.file.SaveAs(path);
                    using (SLDocument sl = new SLDocument(path))
                    {
                        sl.SelectWorksheet("RouteMaster");
                        List<RouteMaster> lRouteMaster = new List<RouteMaster>();

                        int iRow = 2;
                        string[] LogisticsPointsID = { "20TMB", "SDSPT", "MXOTM" };
                        while (!string.IsNullOrEmpty(sl.GetCellValueAsString(iRow, 1)))
                        {
                            if (LogisticsPointsID.Contains(sl.GetCellValueAsString(iRow, 34).Trim()))
                            {                                
                                RouteMaster oRouteMaster = new RouteMaster()
                                {
                                    Hazmat = sl.GetCellValueAsString(iRow, 9),
                                    UnloadDate = sl.GetCellValueAsDateTime(iRow, 10),
                                    RouteRun = sl.GetCellValueAsString(iRow, 11),
                                    Route = sl.GetCellValueAsString(iRow, 12),
                                    Run = sl.GetCellValueAsString(iRow, 13),
                                    PuRoute2 = sl.GetCellValueAsString(iRow, 14),
                                    RouteType = sl.GetCellValueAsString(iRow, 15),
                                    RouteMiles = sl.GetCellValueAsString(iRow, 23),
                                    LegMiles = sl.GetCellValueAsString(iRow, 24),
                                    Seq = sl.GetCellValueAsString(iRow, 25),
                                    SName = sl.GetCellValueAsString(iRow, 29),
                                    LDK = sl.GetCellValueAsString(iRow, 31),
                                    LogisticsPointId = sl.GetCellValueAsString(iRow, 34),
                                    Timezone = sl.GetCellValueAsString(iRow, 39),
                                    RoutesMilestone = sl.GetCellValueAsString(iRow, 42),
                                    Day = sl.GetCellValueAsString(iRow, 40),
                                    ArrvDate = sl.GetCellValueAsDateTime(iRow, 35),
                                    ArrvTime = TimeSpan.Parse(sl.GetCellValueAsString(iRow, 36)),
                                    DepDate = sl.GetCellValueAsDateTime(iRow, 37),
                                    DepTime = TimeSpan.Parse(sl.GetCellValueAsString(iRow, 38)),
                                    PeriodId = periodId,
                                    DataSourceId = 1,
                                    RegisterDate = DateTime.Now.Date
                                };
                                lRouteMaster.Add(oRouteMaster);
                            }
                            iRow++;
                        }
                        DataTable dtblRouteMaster = ConvertToDatatable(lRouteMaster);
                        //Invocar metodo del WCF   
                        string user = User.Identity.GetUserId();
                        bool saved = wcf.saveRouteMaster(dtblRouteMaster, path, user);
                        //Response.Write("Saved: " + importExcel.file.FileName);
                        return RedirectToAction("fileReport");
                    }
                    //ViewBag.Error = 0;
                }
                else {
                    ViewBag.Error = 1;
                }
            }
            return View();
        }

        public ActionResult UploadDTR() {

            ViewBag.error = (wcf.wasFileUploaded(2)) ? 1 : 0;

            return View();
        }

        [HttpPost]
        public ActionResult UploadDTR(ImportExcel importExcel)
        {
            if (ModelState.IsValid)
            {
                string dateStamp = DateTime.Now.ToString("yyyyMMddHHmmss");
                string path = Server.MapPath("~/Content/Uploads/" + dateStamp + "-" + importExcel.file.FileName);
                importExcel.file.SaveAs(path);
                using (SLDocument sl = new SLDocument(path))
                {
                    sl.SelectWorksheet("DTR");
                    List<DTR> lDTR = new List<DTR>();

                    int iRow = 2;
                    while (!string.IsNullOrEmpty(sl.GetCellValueAsString(iRow, 4)))
                    {
                        DTR oDTR = new DTR()
                        {
                            TrailerNumber = sl.GetCellValueAsString(iRow, 1),
                            Route_Seq = sl.GetCellValueAsString(iRow, 2),
                            Renban = sl.GetCellValueAsString(iRow, 3),
                            UnloadDate = sl.GetCellValueAsDateTime(iRow, 4),
                            SecondUnloadDate = sl.GetCellValueAsDateTime(iRow, 5),
                            ShipDate = sl.GetCellValueAsDateTime(iRow, 6),
                            ETAbyXPO = sl.GetCellValueAsDateTime(iRow, 7),
                            Hazmat = sl.GetCellValueAsString(iRow, 8),
                            XBorder = sl.GetCellValueAsDateTime(iRow, 9),
                            CLoadLinesMROS = sl.GetCellValueAsString(iRow, 10),                            
                        };

                        lDTR.Add(oDTR);
                        
                        iRow++;
                    }                    

                    DataTable dtblDTR = ConvertToDatatable(lDTR);
                    string user = User.Identity.GetUserId();
                    int saved = wcf.saveDTR(dtblDTR,path, user);
                    //que paso miiiii montoya
                    //Response.Write("Saved: " + saved +" Rows - "+ importExcel.file.FileName);
                    return RedirectToAction("fileReport");
                }
            }

            return View();
        }

        public ActionResult UploadInvoices() {
            InvoicesImportExcel oImportExcel = new InvoicesImportExcel { listSpotsVM = null };
            return View(oImportExcel);
        }

        [HttpPost]
        public ActionResult UploadInvoices(InvoicesImportExcel importExcel)
        {
            List<SpotsVM> lstSpots = new List<SpotsVM>();
            if (ModelState.IsValid)
            {
                string dateStamp = DateTime.Now.ToString("yyyyMMddHHmmss");
                string path = Server.MapPath("~/Content/Uploads/" + dateStamp + "-" + importExcel.file.FileName);
                importExcel.file.SaveAs(path);

                SLDocument sl = new SLDocument(path);
                
                List<Broker> lBroker = new List<Broker>();

                int iRow = 2;
                while (!string.IsNullOrEmpty(sl.GetCellValueAsString(iRow, 1)))
                {
                    Broker oBroker = new Broker()
                    {
                        Route = sl.GetCellValueAsString(iRow, 1),
                        Sequence = sl.GetCellValueAsString(iRow, 2),
                        TrailerNumber = sl.GetCellValueAsString(iRow, 3),
                        UnloadDate = sl.GetCellValueAsDateTime(iRow, 4),
                        Invoice = sl.GetCellValueAsString(iRow, 5),
                    };

                    lBroker.Add(oBroker);
                    iRow++;
                }
                    
                DataTable dtblBroker = ConvertToDatatable(lBroker);
                string user = User.Identity.GetUserId();
                var saved = wcf.saveBrokerFile(dtblBroker, path, user);

                foreach (var item in saved) {                    
                    SpotsVM oSpotsVM = new SpotsVM();
                    oSpotsVM.trailerNumber = item.trailerNumber;
                    oSpotsVM.yardSpotId = item.yardSpotId;
                    lstSpots.Add(oSpotsVM);
                }                                
            }

            return View(new InvoicesImportExcel { listSpotsVM = lstSpots });
        }

SDSP/Views/Sources/LoadInventory.cshtml
@model SDSP.Models.ImportExcel
@{ ViewBag.Title = "SDSP - Load Inventory";}
<div id="viewContent">
    <h3>Load Inventory</h3>
    @using (Html.BeginForm("LoadInventory", "Sources", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.file, "Select file", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.file, new { type = "file" })
                </div>
                <div class="col-md-10 col-lg-offset-2">
                    @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger", @id = "file-error" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Upload" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

SDSP/Views/Sources/UploadDTR.cshtml
@model SDSP.Models.ImportExcel
@{ ViewBag.Title = "SDSP - Upload DTR File";}
<div id="viewContent">
    <h3>Upload DTR</h3>
    @if (ViewBag.error == 0)
    {
        using (Html.BeginForm("UploadDTR", "Sources", FormMethod.Post, new { enctype = "multipart/form-data", id = "loadFile" }))
        {
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.file, "Select file", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.file, new { type = "file" })
                </div>
                <div class="col-md-10 col-lg-offset-2">
                    @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger", @id = "file-error" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input id="load" type="submit" value="Upload" class="btn btn-default" />
                </div>
            </div>
        </div>
        }

        <div class="modal" id="loadingModal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog" role="document">
                <div class="modal-content">                
                    <div class="modal-body" style="text-align:center;">
                        <img src="~/Content/Images/loading.gif" />
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <h4>A DTR file was already uploaded today.</h4>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customLoading")
}

SDSP/Views/Sources/UploadInTransit.cshtml
@model SDSP.Models.ImportExcel
@{ ViewBag.Title = "SDSP - Upload In Transit File";}
<div id="viewContent">
    <h3>Upload In Transit File</h3>
    @using (Html.BeginForm("UploadInTransit", "Sources", FormMethod.Post, new { enctype = "multipart/form-data", id = "loadFile" }))
    {
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.file, "Select file", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.file, new { type = "file" })
                </div>
                <div class="col-md-10 col-lg-offset-2">
                    @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger", @id = "file-error" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input id="load" type="submit" value="Upload" class="btn btn-default" />
                </div>
            </div>
        </div>

    }
    <div class="modal" id="loadingModal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body" style="text-align:center;">
                    <img src="~/Content/Images/loading.gif" />
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customLoading")
}

SDSP/Views/Sources/UploadInvoices.cshtml
@model SDSP.Models.InvoicesImportExcel
@{ ViewBag.Title = "SDSP - Upload Invoices File";}
<style>
    .table {
        width: 30%;
        margin: 20px auto;
    }
</style>
@if (Model.listSpotsVM == null) {
    <div id="viewContent">
        <h3>Upload Invoices File</h3>
        @using (Html.BeginForm("UploadInvoices", "Sources", FormMethod.Post, new { enctype = "multipart/form-data", id = "loadFile" }))
        {
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.file, "Select file", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.file, new { type = "file" })
                    </div>
                    <div class="col-md-10 col-lg-offset-2">
                        @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger", @id = "file-error" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input id="load" type="submit" value="Upload" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div class="modal" id="loadingModal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body" style="text-align:center;">
                        <img src="~/Content/Images/loading.gif" />
                    </div>
                </div>
            </div>
        </div>
        
    </div>
}
else{
    <h3>Trailers & Sports List</h3>
    <div id="spots-table">
        <table class="table" id="trailers">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Trailer</th>
                    <th>Spot</th>
                </tr>
            </thead>
            <tbody>
                @{int x = 1; }
                @foreach (var item in Model.listSpotsVM){
                    <tr>
                        <td>@x</td>
                        <td>@item.trailerNumber</td>
                        @if (item.yardSpotId > 0){
                            <td style="font-weight:bold;">@item.yardSpotId</td>
                        }
                        else
                        {
                            <td>N/A</td>
                        }
                    </tr>
                    x++;
                }
            </tbody>
        </table>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customLoading")
}

SDSP/Views/Sources/UploadOriginalInTransit.cshtml
@model SDSP.Models.ImportExcel
@{ ViewBag.Title = "SDSP - Upload In Transit File";}
<div id="viewContent">
    <h3>Upload In Transit File</h3>
    @if (ViewBag.error == 0)
    {
        using (Html.BeginForm("UploadOriginalInTransit", "Sources", FormMethod.Post, new { enctype = "multipart/form-data", id = "loadFile" }))
        {
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.file, "Select file", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.file, new { type = "file" })
                    </div>
                    <div class="col-md-10 col-lg-offset-2">
                        @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger", @id = "file-error" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input id="load" type="submit" value="Upload" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        <div class="modal" id="loadingModal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body" style="text-align:center;">
                        <img src="~/Content/Images/loading.gif" />
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <h4>An in transit file was already uploaded today.</h4>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customLoading")
}

SDSP/Views/Sources/UploadRouteMaster.cshtml
@model SDSP.Models.RouteMasterExcel
@{ ViewBag.Title = "SDSP - Upload Route Master File";}
<div id="viewContent">
    <h3>Upload Route Master</h3>
    
        @if (ViewBag.Error == 0)
        {
            using (Html.BeginForm("UploadRouteMaster", "Sources", FormMethod.Post, new { enctype = "multipart/form-data", id = "loadFile" }))            
            {
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.period, "Period", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.period, new { type = "text" })
                    </div>
                    <div class="col-md-10 col-lg-offset-2">
                        @Html.ValidationMessageFor(model => model.period, "", new { @class = "text-danger", @id = "period-error" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2" for="StartDate">Period Start Date</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control datepicker", @type = "date" })
                    </div>
                    <div class="col-md-10 col-lg-offset-2">
                        <span id="start-date-error" class="field-validation-valid text-danger" data-valmsg-for="StartDate" data-valmsg-replace="true"></span>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.file, "Select file", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.file, new { type = "file" })
                    </div>
                    <div class="col-md-10 col-lg-offset-2">
                        @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger", @id = "file-error" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input id="load" type="submit" value="Upload" class="btn btn-default" />
                    </div>
                </div>
            </div>
            }
            <div class="modal" id="loadingModal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-body" style="text-align:center;">
                            <img src="~/Content/Images/loading.gif" />
                        </div>
                    </div>
                </div>
            </div>
        }
        else {
            <h2>There is a routemaster file uploaded for that period, This one wasn't uploaded.</h2>
        }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customLoading")
}

SDSP/Views/Sources/fileReport.cshtml
@model SDSP.Models.FilesReportVM
@{
    ViewBag.Title = "Uploaded files report";
}
<style>
    #report-data {
        font-weight: bold;
        font-size: 15px;
    }

    #submitButton {
        margin-bottom: 20px;
    }
</style>
<h2>Uploaded files report</h2>

<div id="searchTerms">
    @using (Html.BeginForm("fileReport", "Sources", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            <label class="control-label col-md-2" for="startDate">Start Date</label>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.startDate, new { @class = "form-control datepicker", @type = "date" })
            </div>
            <div class="col-md-10 col-lg-offset-2">
                <span id="start-date-error" class="field-validation-valid text-danger" data-valmsg-for="startDate" data-valmsg-replace="true"></span>
            </div>
        </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="endDate">End Date</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.endDate, new { @class = "form-control datepicker", @type = "date" })
                </div>
                <div class="col-md-10 col-lg-offset-2">
                    <span id="end=date-error" class="field-validation-valid text-danger" data-valmsg-for="endDate" data-valmsg-replace="true"></span>
                </div>
            </div>
            <button id="submitButton" type="submit">Get Report</button>
    }
</div>

<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title" id="delete-title">Confirm Delete</h2>
            </div>
            <div class="modal-body">
                Are you sure you want to delete the selected record?
            </div>
            <div class="modal-footer">
                <button type="button" id="yes" class="btn btn-primary" data-dismiss="modal">Yes</button>
                <button type="button" id="no" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

@if (Model.fileList.Count > 0)
{
    <span id="report-data">From @Model.startDate.ToShortDateString() to @Model.endDate.ToShortDateString()</span>
        <div id="divMessage" class="alert alert-success collapse">
            <a id="closeMessage" class="close" href="#">&times;</a>
            <h4 class="alert-heading">Deleted successfully!</h4>
        </div>
        <table id="Trailers" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>File Name</th>
                    <th>Upload Date</th>
                    <th>File type</th>
                    <th></th>
            </thead>
            <tbody>
                @foreach (var rm in Model.fileList)
                {
                    string[] splitString = rm.FileName.Split('\\');
                    string name = splitString[splitString.Count()-1];
                    <tr>
                        <td>@name</td>
                        <td>@rm.UploadDate</td>
                        <td>@rm.Name</td>
                        <td><a href="~/Content/Uploads/@name">Download</a></td>
                    </tr>
                }
            </tbody>
        </table>

        @*<input type="submit" id="btnSubmit" value="Download as Excel" />*@
}
else
{
    <h2>No files data found for the specified dates.</h2>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @*@Scripts.Render("~/bundles/ingatesReport")*@
}

SDSP/Views/Sources/updatePriorities.cshtml
@model IEnumerable<SDSP.Models.RealTime_InTransit>
@{
    ViewBag.Title = "updatePriorities";
}
@Styles.Render("~/Content/jqueryui")
<style>
    #current {
        /*float:left;
        width:50%;*/
    }

    #plusone {
        /*float:left;
        width:30%;*/
    }

    #plustwo {
        /*width:30%;
        float:left;*/
    }
    .updownrow {
        padding: 15px;
    }
    .updownbtn {
        font-size: 12px;
    }
    #loading {
        display:    none;
        position:   fixed;
        z-index:    1000;
        top:        0;
        left:       0;
        height:     100%;
        width:      100%;
        background: rgba( 255, 255, 255, .8 ) 
                    url('https://i.gifer.com/EXfZ.gif') 
                    50% 50% 
                    no-repeat;
    }
    .hidden-row {
        visibility:collapse;
    }
</style>
<h2>Update Priorities</h2>
<div id="divMessage" class="alert alert-success collapse">
    <a id="closeMessage" class="close" href="#">&times;</a>
    <h4 class="alert-heading">Saved successfully!</h4>
</div>
@Html.Label("Elements from the list can be dragged up or down to a new position or sent to the top by pressing the button.", htmlAttributes: new { @class = "col-md-10" })
<div id="tablas">
    <div class="row">
        <div class="col-sm-12">
            <table id="current" class="table">
                <thead>
                    <tr>
                        @*<th>Order</th>*@
                        <th>Priority</th>
                        <th>Trailer Number</th>
                        <th>Route-Origin</th>
                        <th>Hazmat</th>
                        <th>Invoice</th>
                        <th>Unload Date</th>
                        <th>Pull Ahead</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        string clase = "";
                        if (@item.outTime != null)
                        {
                            clase = "hidden-row";
                        }
                        string routeRun = (item.Run == "") ? item.Route : item.Route + "-" + item.Run;
                        <tr id="@item.Id" class="@clase">
                            @*<td>@item.ExpressPriority</td>*@
                            <td>@item.Priority</td>
                            <td>@item.TrailerNumber</td>
                            <td>@routeRun</td>
                            <td>@item.Hazmat</td>
                            <td>@item.Invoice</td>
                            <td>@item.UnloadDate</td>
                            <td>@item.PullAhead</td>
                            <td>
                                <button type="button" class="updownbtn movetop fa fa-angle-double-up">Send to top</button>
                                @*<button type="button" class="updownbtn movebottom fa fa-angle-double-down">To Bottom</button>*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>        
    </div>
    @*Animacion de loading*@
    <div class="modal" id="loadingModal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body" style="text-align:center;">
                    <img src="~/Content/Images/loading.gif" />
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Comentarios -->
    <div class="modal fade" id="commentsModal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="comment-title">Reason for the change</h2>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        @Html.Label("Please add a reason for the change", htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.TextArea("Comment", null, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="cancelChange" type="button" class="btn btn-secondary">Cancel change</button>
                    <button id="saveChange" type="button" class="btn btn-primary">Save reason</button>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customUpdatePriorities")
}