SDSP/Models/Outgate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SDSP.Models
{
    public class Outgate
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> DriverId { get; set; }
        public Nullable<long> RouteMasterId { get; set; }
    }

    public class DispatchInfo{
        public Driver Driver { get; set; }
        public RouteMaster RouteMaster { get; set; }
    }
}

SDSP/Models/OutgatesReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SDSP.Models
{
    public class OutgatesReport
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> OutgateDateTime { get; set; }
        public Nullable<long> OutgateDriverId { get; set; }
        public Nullable<long> OutgateRouteMasterId { get; set; }
        public long IdDriver { get; set; }
        public Nullable<long> IdCamex { get; set; }
        public string DriverName { get; set; }
        public Nullable<long> IdCompany { get; set; }
        public string AspNetUsersId { get; set; }
        public long CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyUserId { get; set; }
        public long idRouteMaster { get; set; }
        public string Hazmat { get; set; }
        public Nullable<System.DateTime> UnloadDate { get; set; }
        public string RouteRun { get; set; }
        public string Route { get; set; }
        public string Run { get; set; }
        public string PuRoute2 { get; set; }
        public string RouteType { get; set; }
        public string RouteMiles { get; set; }
        public string LegMiles { get; set; }
        public string Seq { get; set; }
        public string SName { get; set; }
        public string LDK { get; set; }
        public string LogisticsPointId { get; set; }
        public Nullable<System.DateTime> ArrvDate { get; set; }
        public Nullable<System.TimeSpan> ArrvTime { get; set; }
        public Nullable<System.DateTime> DepDate { get; set; }
        public Nullable<System.TimeSpan> DepTime { get; set; }
        public string Timezone { get; set; }
        public string RoutesMilestone { get; set; }
        public string Day { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string TrailerNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<int> DataSourceId { get; set; }
        public Nullable<int> ExpressPriority { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> PullAhead { get; set; }
        public Nullable<long> RouteMasterId { get; set; }
        public long Expr1 { get; set; }
        public Nullable<int> Bound { get; set; }
    }

    public class OutgatesReportVM
    {
        public DateTime startDate { get; set; }
        public DateTime endDate { get; set; }
        public List<OutgatesReport> outgatesReport { get; set; }
    }
}

SDSP/Controllers/OutgatesController.cs
using Microsoft.AspNet.Identity;
using SDSP.Class;
using SDSP.Models;
using SpreadsheetLight;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SDSP.Controllers
{
    [Authorize]
    public class OutgatesController : Controller
    {
        ServiceReference1.SDSPServiceClient wcf = new ServiceReference1.SDSPServiceClient();
        DataSourceHelper dsh = new DataSourceHelper();
        // GET: Outgates
        public ActionResult Index()
        {
            return View();
        }

        // GET: Outgates/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        
        // GET: Outgates/Create
        public ActionResult Create()
        {
            ViewBag.DriverId = dsh.getDrivers();

            ViewBag.CompanyId = dsh.getCompanies();

            return View();
        }        

        // POST: Outgates/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,RouteMasterId,DateTime")] Outgate outgate)
        {
            try
            {
                // TODO: Add insert logic here
                

                //return RedirectToAction("Index");
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Outgates/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Outgates/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        // GET: Outgates/Delete/5
        public JsonResult Delete(int id)
        {
            string user = User.Identity.GetUserId();
            bool outgate = wcf.deleteDispatch(id, user);
            return Json(new { deleted = outgate });
        }

        public JsonResult GetTrailers()
        {
            var trailerlst = wcf.GetPreoutgateTrailers();

            List<PrintHookVM> Trailers = new List<PrintHookVM>();

            foreach (var item in trailerlst)
            {
                PrintHookVM phObj = new PrintHookVM();

                phObj.Driver = new Driver
                {
                    Id = item.Driver.Id,
                    Name = item.Driver.Name
                };
                phObj.PreOutgate = new PreOutgate
                {
                    Id = item.PreOutgate.Id
                };
                phObj.Company = new Company
                {
                    Id = item.Company.Id,
                    Name = item.Company.Name
                };
                phObj.RouteMaster = new RouteMaster
                {
                    Id = item.RouteMaster.Id,
                    Route = item.RouteMaster.Route,
                    Seq = item.RouteMaster.Run,
                    Priority = item.RouteMaster.Priority,
                    UnloadDate = item.RouteMaster.UnloadDate,
                    TrailerNumber = item.RouteMaster.TrailerNumber,
                    ExpressPriority = item.RouteMaster.ExpressPriority,
                    Comments = item.RouteMaster.Comments
                };

                phObj.Ingate = new Ingate {
                    Id = item.Ingate.Id,
                    YardSpotId = item.Ingate.YardSpotId
                };
                Trailers.Add(phObj);
            }

            return Json(Trailers, JsonRequestBehavior.AllowGet);
        }

        public JsonResult saveDispatch(IDictionary<string,int> trailers) {
            var newDict = new Dictionary<string, int>(trailers);

            string user = User.Identity.GetUserId();
            var savedOutgates = wcf.saveDispatches(newDict, user);                                               

            return Json(new { saved = savedOutgates });
        }

        public JsonResult updateDriver(int preoutgateId, int newDriver) {
            string user = User.Identity.GetUserId();
            var updated = wcf.updateAssignedDriver(preoutgateId, newDriver, user);

            return Json(new { wasupdated = updated});
        }

        public JsonResult assignDriver(long? routeMasterid, long? newDriver) {
            string AspNetUsersId = User.Identity.GetUserId();
            var assigned = wcf.SavePreOutGate(routeMasterid, newDriver, AspNetUsersId);

            return Json(new { wasupdated = assigned });
        }

        public JsonResult saveSkipReasons(int routeMasterId, string reason) {
            string user = User.Identity.GetUserId();
            bool result = wcf.saveSkipReasons(routeMasterId,reason, user);

            return Json(new { saved = result });
        }


        public ActionResult outgatesReport()
        {
            OutgatesReportVM oReport = new OutgatesReportVM();
            List<OutgatesReport> oList = new List<OutgatesReport>();
            DateTime start = DateTime.Now.Date;
            DateTime end = start.AddDays(1).Date;
            var result = wcf.OutgatesReport(start, end);

            foreach (var item in result)
            {
                OutgatesReport oObj = new OutgatesReport
                {
                    Id = item.Id,
                    OutgateRouteMasterId = item.OutgateRouteMasterId,
                    OutgateDriverId = item.OutgateDriverId,
                    OutgateDateTime = item.OutgateDateTime,
                    CompanyName = item.CompanyName,
                    DriverName = item.DriverName,
                    TrailerNumber = item.TrailerNumber,
                    Route = item.Route,
                    Run = item.Run,
                    UnloadDate = item.UnloadDate,
                    Bound = item.Bound
                };

                oList.Add(oObj);
            }

            oReport.startDate = start;
            oReport.endDate = end;
            oReport.outgatesReport = oList;

            ViewBag.YardSpotId = dsh.getSpotstoChange();

            return View(oReport);
        }

        [HttpPost]
        public ActionResult outgatesReport(OutgatesReportVM outgatesReport)
        {
            OutgatesReportVM oReport = new OutgatesReportVM();
            List<OutgatesReport> oList = new List<OutgatesReport>();
            DateTime end = outgatesReport.endDate.AddMinutes(1439);
            var result = wcf.OutgatesReport(outgatesReport.startDate, end);

            foreach (var item in result)
            {
                OutgatesReport oObj = new OutgatesReport
                {
                    Id = item.Id,
                    OutgateRouteMasterId = item.OutgateRouteMasterId,
                    OutgateDriverId = item.OutgateDriverId,
                    OutgateDateTime = item.OutgateDateTime,
                    CompanyName = item.CompanyName,
                    DriverName = item.DriverName,
                    TrailerNumber = item.TrailerNumber,
                    Route = item.Route,
                    Run = item.Run,
                    UnloadDate = item.UnloadDate,
                    Bound = item.Bound
                };

                oList.Add(oObj);
            }

            oReport.startDate = outgatesReport.startDate;
            oReport.endDate = outgatesReport.endDate;
            oReport.outgatesReport = oList;

            ViewBag.YardSpotId = dsh.getSpotstoChange();

            return View(oReport);
        }

        public JsonResult changeSpot(long? routeMasterId, int newSpot)
        {
            string user = User.Identity.GetUserId();
            bool saved = wcf.changeDispatchSpot(routeMasterId, newSpot, user);

            return Json(new { saved = saved });
        }

        public FileResult Export(string start, string end)
        {
            DateTime startDate = new DateTime();
            DateTime endDate = new DateTime();
            if (start == "" && end == "")
            {
                startDate = DateTime.Now.Date;
                endDate = startDate.AddDays(1).Date;
            }            
            else
            {
                startDate = DateTime.Parse(start);
                endDate = DateTime.Parse(end);
                endDate = endDate.AddDays(1).Date;
            }
            var result = wcf.OutgatesReport(startDate, endDate);

            string dateStamp = DateTime.Now.ToString("yyyyMMddHHmmss");
            string fileName = "OutgateReport-"+dateStamp+".xlsx";
            string path = Server.MapPath("~/Content/Uploads/" + fileName);

            SLDocument oSLDocument = new SLDocument();

            System.Data.DataTable dt = new System.Data.DataTable();

            //columnas
            dt.Columns.Add("Trailer", typeof(string));
            dt.Columns.Add("Route", typeof(string));
            dt.Columns.Add("Sequence", typeof(string));
            dt.Columns.Add("Unload Date", typeof(string));
            dt.Columns.Add("Outgate Date & Time", typeof(string));
            dt.Columns.Add("Driver", typeof(string));
            dt.Columns.Add("Bound", typeof(string));

            foreach (var item in result)
            {
                string bound = (item.Bound == 1) ? "Southbound" : "Northbound";
                dt.Rows.Add(item.TrailerNumber, item.Route, item.Run, item.UnloadDate, item.OutgateDateTime, item.DriverName, bound);
            }

            oSLDocument.ImportDataTable(1, 1, dt, true);

            oSLDocument.SaveAs(path);

            byte[] fileBytes = System.IO.File.ReadAllBytes(path);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public JsonResult reloadoutgatesReport(string startDate, string endDate)
        {

SDSP/Views/Outgates/Create.cshtml
@model SDSP.Models.Outgate
@Styles.Render("~/Content/jqueryui")
<h2>Outgate</h2>
<style>
    .custom-combobox-input {
        width: 280px;
        height: 30px;
        background: white;
        border-radius: 3px;
        padding: 10px;
    }
    .selected {
        background-color: #F39814;
        color: white;
    }
    .ui-autocomplete.ui-menu {
      z-index: 3001;
    } 
    #divTrailers {
        max-height: 490px;
        overflow-y: auto;
    }
    #reasons-container {
        max-height: 300px;
        overflow-y: auto;
    }
    #searchOutgate {
        margin-left:10px;
    }
</style>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">           
            <div id="divMessage" class="alert alert-success collapse">
                <a id="closeMessage" class="close" href="#">&times;</a>
                <h4 class="alert-heading">Saved successfully!</h4>
            </div>
            <div id="divError" class="alert alert-danger collapse">
                <a id="closeErrorMessage" class="close" href="#">&times;</a>
                <h4 id ="errorText" class="alert-heading">No rows were selected</h4>
            </div>
            <div id="divWarning" class="alert alert-warning collapse">
                <a id="closeWarning" class="close" href="#">&times;</a>
                <h4 id="warningText" class="alert-heading">Some were repeated</h4>
            </div>
            <div class="col-md-12" style="text-align:right">
                <input id="btnTrailers" type="submit" value="Reload Trailer List" class="btn btn-default" />
                <input id="dispatch" type="submit" value="Dispatch" class="btn btn-primary" />
            </div>
            @Html.Label("Click or hit space on a row to select trailers for dispatch.", htmlAttributes: new { @class = "col-md-10" })            
            <div id="divTrailers" class="col-md-12">
                <label>Search</label><input id="searchOutgate" type="text" placeholder="Trailer # or Driver">
                <table class="table" id="trailers">
                    <thead>
                        <tr>
                            <th>Trailer #</th>
                            <th>Spot #</th>
                            <th>Priority</th>
                            <th>Comments</th>
                            <th>Assigned Driver</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            @Html.Hidden("ingateId")
        </div>
        <div class="modal fade" id="tblEditDriverModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h2 class="modal-title" id="tblEditDriver-title"></h2>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.DriverId, "New Driver", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-8">
                                @Html.DropDownList("DriverId", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="col-md-10 col-lg-offset-2">
                                @Html.ValidationMessageFor(model => model.DriverId, "", new { @class = "text-danger", @id = "driver-error" })
                            </div>
                        </div>

                        <div id="divAddDriver" class="dynamic-modal-form collapse">
                            <a id="closeDriver" class="close" href="#">&times;</a>
                            <h3>Add Driver</h3>
                            <div class="form-group">
                                <label class="control-label col-md-2" for="DriverName">Name</label>
                                <div class="col-md-10">
                                    <input class="form-control text-box single-line" data-val="false" data-val-number="" id="DriverName" name="DriverName" type="text" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-2" for="CompanyId">Company</label>
                                <div class="col-md-10">
                                    @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                                </div>
                                <div class="col-md-10 col-lg-offset-2">
                                    <span id="company-error" class="field-validation-valid text-danger" data-valmsg-for="DriverName" data-valmsg-replace="true"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save Driver" id="save-driver" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                        <div id="divAddCompany" class="dynamic-modal-form collapse">
                            <a id="closeCompany" class="close" href="#">&times;</a>
                            <h3>Add Company</h3>
                            <div class="form-group">
                                <label class="control-label col-md-2" for="CompanyName">Name</label>
                                <div class="col-md-10">
                                    <input class="form-control text-box single-line" data-val="false" data-val-number="" id="CompanyName" name="CompanyName" type="text" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save Company" id="save-company" class="btn btn-default" />
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button id="change-driver" type="button" class="btn btn-secondary" data-dismiss="modal">Save New Driver</button>
                    </div>
                </div>
            </div>
        </div>

        @*<div class="form-group">
            <div class="col-md-10">
                <input id="dispatch" type="submit" value="Dispatch" class="btn btn-default" />
            </div>
        </div>*@
    </div>

    <!-- Modal para escribir razones de prioridades saltadas -->
    <div class="modal fade" id="skippedModal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="comment-title">Reasons</h2>
                </div>
                <div class="modal-body">
                    <div id="reasons-container">
                        <table id="reasons" class="table">
                            <thead>
                                <tr>
                                    <th>Trailer</th>
                                    <th>Reason for skipping it</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
                @*<div class="modal-footer">
                    
                </div>*@
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customoutgate")
}

SDSP/Views/Outgates/outgatesReport.cshtml
@model SDSP.Models.OutgatesReportVM
@{
    ViewBag.Title = "Out Gate Report";
}
<style>
    #report-data {
        font-weight: bold;
        font-size: 15px;
    }

    #submitButton {
        margin-bottom: 20px;
    }
</style>
<h2>Out Gate Report</h2>

<div id="searchTerms">
    @using (Html.BeginForm("outgatesReport", "Outgates", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            <label class="control-label col-md-2" for="startDate">Start Date</label>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.startDate, new { @class = "form-control datepicker", @type = "date" })
            </div>
            <div class="col-md-10 col-lg-offset-2">
                <span id="start-date-error" class="field-validation-valid text-danger" data-valmsg-for="startDate" data-valmsg-replace="true"></span>
            </div>
        </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="endDate">End Date</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.endDate, new { @class = "form-control datepicker", @type = "date" })
                </div>
                <div class="col-md-10 col-lg-offset-2">
                    <span id="end=date-error" class="field-validation-valid text-danger" data-valmsg-for="endDate" data-valmsg-replace="true"></span>
                </div>
            </div>
            <button id="submitButton" type="submit">Get Report</button>
    }
</div>
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title" id="delete-title">Confirm Delete</h2>
            </div>
            <div class="modal-body">
                Are you sure you want to delete the selected record?
            </div>
            <div class="modal-footer">
                <button type="button" id="yes" class="btn btn-primary" data-dismiss="modal">Yes</button>
                <button type="button" id="no" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
@if (Model.outgatesReport.Count > 0)
{
    <span id="report-data">From @Model.startDate.ToShortDateString() to @Model.endDate.ToShortDateString()</span>
    <div id="divMessage" class="alert alert-success collapse">
        <a id="closeMessage" class="close" href="#">&times;</a>
        <h4 class="alert-heading">Deleted successfully!</h4>
    </div>
    <label style="margin-left: 15px;">Search</label><input id="search" type="text" placeholder="Trailer #" />
    <table id="Trailers" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Trailer</th>
                <th>Route</th>
                <th>Sequence</th>
                @*<th>Unload Date</th>*@
                <th>Outgate Date & Time</th>
                <th>Driver</th>
                <th>Bound</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var rm in Model.outgatesReport)
            {
                string bound = (rm.Bound == 1) ? "Southbound" : "Northbound";
                <tr>
                    <td>@rm.TrailerNumber</td>
                    <td>@rm.Route</td>
                    <td>@rm.Run</td>
                    @*<td>@rm.UnloadDate</td>*@                    
                    <td>@rm.OutgateDateTime</td>
                    <td>@rm.DriverName</td>
                    <td>@bound</td>
                    <td><a id="Delete-@(rm.Id+"-"+rm.OutgateRouteMasterId)" href="#">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
    <input type="submit" id="btnSubmit" value="Export to Excel" />

    @*Modal para informar que el spot original ha sido ocupado y escoger un nuevo spot*@
    <div class="modal fade" id="changeSpotModal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="comment-title">Select spot</h2>
                </div>
                <div class="modal-body">
                    <label class = "control-label col-md-12">The previous yard spot for this trailer has been occupied, please choose a new yard spot.</label>
                    <div class="form-group">                        
                        <div class="col-md-12">
                            @Html.DropDownList("YardSpotId", null, htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="change-spot" type="button" class="btn btn-primary collapse" data-dismiss="modal">Save New Spot</button>
                    <button id="close-comment" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    @*Modal para informar si se cambio el spot o no*@
    <div class="modal fade" id="resultModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="resultText">
                </div>
            </div>
        </div>
    </div>
}
else
{
    <h2>No out gate data found for the specified dates.</h2>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/outgatesReport")
}